"""add dispatch_prompt to threads

Revision ID: 5772beaffd0c
Revises: 69385eaa54bb
Create Date: 2026-05-25 14:12:06.529454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5772beaffd0c'
down_revision: Union[str, Sequence[str], None] = '69385eaa54bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('dispatch_prompt', sa.Text(), nullable=True, comment='主 Agent 派活时给子 Agent 的指令，_run_thread 启动 Adapter 时塞进 StreamInput.prompt'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threads', 'dispatch_prompt')
    # ### end Alembic commands ###
