"""add_oauth_fields_to_users

Revision ID: 642b2725e844
Revises: 5772beaffd0c
Create Date: 2026-06-08 11:00:19.328175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '642b2725e844'
down_revision: Union[str, Sequence[str], None] = '5772beaffd0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=20), nullable=True, comment='OAuth 提供方，如 microsoft'))
    op.add_column('users', sa.Column('oauth_subject', sa.String(length=100), nullable=True, comment='OAuth 提供方的用户唯一 ID (oid/sub)'))
    op.add_column('users', sa.Column('oauth_tenant_id', sa.String(length=36), nullable=True, comment='AAD 租户 ID，multi-tenant 场景用'))
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               comment='bcrypt 哈希；OAuth 用户为 NULL',
               existing_comment='bcrypt 哈希')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               comment='bcrypt 哈希',
               existing_comment='bcrypt 哈希；OAuth 用户为 NULL')
    op.drop_column('users', 'oauth_tenant_id')
    op.drop_column('users', 'oauth_subject')
    op.drop_column('users', 'oauth_provider')
    # ### end Alembic commands ###
