"""init schema

Revision ID: 69385eaa54bb
Revises: 
Create Date: 2026-05-25 11:08:51.524456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69385eaa54bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_skills',
    sa.Column('agent_id', sa.String(length=36), nullable=False, comment='agents.id'),
    sa.Column('skill_id', sa.String(length=36), nullable=False, comment='skills.id'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('agent_id', 'skill_id')
    )
    op.create_index('ix_agent_skills_skill', 'agent_skills', ['skill_id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment="创建者 user_id；'GUGA'=系统内置"),
    sa.Column('name', sa.String(length=100), nullable=False, comment='联系人列表展示名'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Agent 简介，联系人卡片副标题'),
    sa.Column('avatar', sa.String(length=500), nullable=True, comment='Agent 头像 URL；为空时前端用首字母色块兜底'),
    sa.Column('type', sa.Enum('claude', 'codex', 'opencode', 'custom', name='agent_type'), nullable=False, comment='路由到对应 Adapter'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='Agent 人格定义'),
    sa.Column('capabilities', sa.JSON(), nullable=True, comment='{"supports_diff":true,"supports_approval":true}'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='["python","code-review"]'),
    sa.Column('is_public', sa.SmallInteger(), server_default='0', nullable=False, comment='公开/私有'),
    sa.Column('is_active', sa.SmallInteger(), server_default='1', nullable=False, comment='启用/停用'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agents_public_active', 'agents', ['is_public', 'is_active'], unique=False)
    op.create_index('ix_agents_user_active', 'agents', ['user_id', 'is_active'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('user_id', sa.String(length=36), nullable=True, comment='谁触发的，系统操作时为 NULL'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='行为标识，如 login / agent.create / diff.apply / approval.confirm'),
    sa.Column('target_type', sa.String(length=50), nullable=True, comment='agent / conversation / message ...'),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True, comment='输入参数 / 变更前后值'),
    sa.Column('ip', sa.String(length=45), nullable=True, comment='客户端 IP（IPv6 最长 45）'),
    sa.Column('user_agent', sa.String(length=255), nullable=True, comment='浏览器 UA'),
    sa.Column('trace_id', sa.String(length=36), nullable=True, comment='关联运行日志 trace_id'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_action_created', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_target', 'audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_index('ix_audit_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('conversation_agents',
    sa.Column('conversation_id', sa.String(length=36), nullable=False, comment='conversations.id'),
    sa.Column('agent_id', sa.String(length=36), nullable=False, comment='agents.id'),
    sa.Column('joined_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='加入时间，群成员按加入顺序展示'),
    sa.Column('is_active', sa.SmallInteger(), server_default='1', nullable=False, comment='是否仍在群里（踢出后置 0，历史消息不丢）'),
    sa.PrimaryKeyConstraint('conversation_id', 'agent_id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='多用户隔离'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='会话标题'),
    sa.Column('mode', sa.Enum('single', 'group', name='conversation_mode'), nullable=False, comment='chat_service 路由分支用'),
    sa.Column('is_pinned', sa.SmallInteger(), server_default='0', nullable=False, comment='置顶'),
    sa.Column('is_archived', sa.SmallInteger(), server_default='0', nullable=False, comment='归档'),
    sa.Column('last_message_preview', sa.String(length=200), nullable=True, comment='最后一条消息摘要，会话列表展示'),
    sa.Column('last_message_at', sa.TIMESTAMP(), nullable=True, comment='最后一条消息时间，比 updated_at 更精确'),
    sa.Column('message_count', sa.Integer(), server_default='0', nullable=False, comment='消息总数'),
    sa.Column('unread_count', sa.Integer(), server_default='0', nullable=False, comment='未读数，前端 badge'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_user_last_msg', 'conversations', ['user_id', 'last_message_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False, comment='messageId'),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=True, comment='关联 threads 表'),
    sa.Column('parent_id', sa.String(length=36), nullable=True, comment='树形结构（重新生成/分支）'),
    sa.Column('user_id', sa.String(length=36), nullable=True, comment='用户消息时填'),
    sa.Column('agent_id', sa.String(length=36), nullable=True, comment='Agent 消息时填'),
    sa.Column('role', sa.Enum('user', 'assistant', name='message_role'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False, comment='ContentBlock 数组的 JSON 序列化（见 domain/message.py）'),
    sa.Column('status', sa.Enum('streaming', 'done', 'error', name='message_status'), server_default='done', nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True, comment='实际用的模型快照，hover 气泡显示'),
    sa.Column('sender', sa.String(length=100), nullable=True, comment='Agent 显示名快照，避免每次 join agents'),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='Agent 响应耗时'),
    sa.Column('feedback', sa.Enum('up', 'down', name='message_feedback'), nullable=True, comment='用户点赞/点踩'),
    sa.Column('selected_range', sa.JSON(), nullable=True, comment='{"file","start","end","code"}，对话式局部修改'),
    sa.Column('is_deleted', sa.SmallInteger(), server_default='0', nullable=False, comment='软删除'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conv_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_messages_thread', 'messages', ['thread_id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='英文唯一标识，对应 .md 文件名'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='中文展示名'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='frontmatter description，progressive disclosure 时塞进系统 prompt'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='分类（代码/安全/领域知识等）'),
    sa.Column('file_path', sa.String(length=255), nullable=False, comment='指向 skills/{name}.md'),
    sa.Column('author_id', sa.String(length=36), nullable=False, comment="创建者 user_id；'GUGA'=系统内置"),
    sa.Column('is_public', sa.SmallInteger(), server_default='0', nullable=False, comment='公开/私有'),
    sa.Column('is_active', sa.SmallInteger(), server_default='1', nullable=False, comment='启用/停用'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id', 'name', name='uq_skills_author_name')
    )
    op.create_index('ix_skills_public_active', 'skills', ['is_public', 'is_active'], unique=False)
    op.create_table('threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False, comment='触发本 Thread 的用户消息'),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('init', 'running', 'suspended', 'done', 'error', 'cancelled', name='thread_status'), server_default='init', nullable=False),
    sa.Column('checkpoint', sa.JSON(), nullable=True, comment='冷存储，热缓存在 Redis'),
    sa.Column('blocked_by', sa.JSON(), nullable=True, comment='任务依赖图：依赖的 thread_id 数组，全部 done 后该 Thread 才解锁启动'),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True, comment='进入 running 时间'),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=True, comment='进入 done/error 时间'),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('tokens_total', sa.Integer(), server_default='0', nullable=False, comment='累计 token 消耗（输入+输出）'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_threads_conv_agent_updated', 'threads', ['conversation_id', 'agent_id', 'updated_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='bcrypt 哈希'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='昵称，前端显示用'),
    sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True, comment='上次登录时间'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index('ix_threads_conv_agent_updated', table_name='threads')
    op.drop_table('threads')
    op.drop_index('ix_skills_public_active', table_name='skills')
    op.drop_table('skills')
    op.drop_index('ix_messages_thread', table_name='messages')
    op.drop_index('ix_messages_conv_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversations_user_last_msg', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('conversation_agents')
    op.drop_index('ix_audit_user_created', table_name='audit_logs')
    op.drop_index('ix_audit_target', table_name='audit_logs')
    op.drop_index('ix_audit_action_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_agents_user_active', table_name='agents')
    op.drop_index('ix_agents_public_active', table_name='agents')
    op.drop_table('agents')
    op.drop_index('ix_agent_skills_skill', table_name='agent_skills')
    op.drop_table('agent_skills')
    # ### end Alembic commands ###
