"""add_workflows_table

Revision ID: 909725750cbd
Revises: 5772beaffd0c
Create Date: 2026-06-04 15:17:03.291644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '909725750cbd'
down_revision: Union[str, Sequence[str], None] = '5772beaffd0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('trigger_message_id', sa.String(length=36), nullable=True),
    sa.Column('threads', sa.JSON(), nullable=False, comment='WorkflowThread[] 的 JSON 序列化'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workflows_conv_created', 'workflows', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_workflows_user', 'workflows', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflows_user', table_name='workflows')
    op.drop_index('ix_workflows_conv_created', table_name='workflows')
    op.drop_table('workflows')
    # ### end Alembic commands ###
