"""add_mcp_tokens_table

Revision ID: 921fee2a08d5
Revises: a757a3297e0e
Create Date: 2026-07-08 17:19:26.106197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '921fee2a08d5'
down_revision: Union[str, Sequence[str], None] = 'a757a3297e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment="用户 ID；Client Credentials 用 'GUGA'"),
    sa.Column('server_id', sa.String(length=100), nullable=False, comment='mcp_servers.id'),
    sa.Column('access_token', sa.Text(), nullable=False, comment='OAuth access token'),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False, comment='过期时间（UTC）'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'server_id', name='uq_mcp_tokens_user_server')
    )
    op.create_index('ix_mcp_tokens_user_server', 'mcp_tokens', ['user_id', 'server_id'], unique=False)
    op.alter_column('agents', 'type',
               existing_type=mysql.ENUM('claude', 'codex', 'opencode', 'custom', 'anthropic_sdk', collation='utf8mb4_unicode_ci'),
               comment='路由到对应 Adapter',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'type',
               existing_type=mysql.ENUM('claude', 'codex', 'opencode', 'custom', 'anthropic_sdk', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='路由到对应 Adapter',
               existing_nullable=False)
    op.drop_index('ix_mcp_tokens_user_server', table_name='mcp_tokens')
    op.drop_table('mcp_tokens')
    # ### end Alembic commands ###
