"""expand_skills_description_to_2000

Revision ID: a757a3297e0e
Revises: 811ed44c244d
Create Date: 2026-06-18 15:41:11.999294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a757a3297e0e'
down_revision: Union[str, Sequence[str], None] = '811ed44c244d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'type',
               existing_type=mysql.ENUM('claude', 'codex', 'opencode', 'custom', 'anthropic_sdk', collation='utf8mb4_unicode_ci'),
               comment='路由到对应 Adapter',
               existing_nullable=False)
    op.alter_column('mcp_servers', 'transport',
               existing_type=mysql.ENUM('stdio', 'sse', 'streamable_http', collation='utf8mb4_unicode_ci'),
               comment='连接方式',
               existing_nullable=False)
    op.alter_column('mcp_servers', 'args',
               existing_type=mysql.JSON(),
               comment='stdio: ["--arg1","val1"]',
               existing_comment='stdio args',
               existing_nullable=True)
    op.alter_column('mcp_servers', 'env',
               existing_type=mysql.JSON(),
               comment='stdio: {"KEY":"value"}',
               existing_comment='stdio env',
               existing_nullable=True)
    op.alter_column('mcp_servers', 'headers',
               existing_type=mysql.JSON(),
               comment='sse: {"Authorization":"Bearer ..."}',
               existing_comment='sse headers',
               existing_nullable=True)
    op.alter_column('mcp_servers', 'author_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment="创建者 user_id；'GUGA'=系统内置",
               existing_comment="创建者；'GUGA'=系统内置",
               existing_nullable=False)
    op.alter_column('mcp_servers', 'is_public',
               existing_type=mysql.SMALLINT(),
               comment='公开/私有',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('mcp_servers', 'is_active',
               existing_type=mysql.SMALLINT(),
               comment='启用/停用',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('mcp_servers', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('skills', 'description',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               type_=sa.String(length=2000),
               existing_comment='frontmatter description，progressive disclosure 时塞进系统 prompt',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skills', 'description',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               existing_comment='frontmatter description，progressive disclosure 时塞进系统 prompt',
               existing_nullable=True)
    op.alter_column('mcp_servers', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('mcp_servers', 'is_active',
               existing_type=mysql.SMALLINT(),
               comment=None,
               existing_comment='启用/停用',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('mcp_servers', 'is_public',
               existing_type=mysql.SMALLINT(),
               comment=None,
               existing_comment='公开/私有',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('mcp_servers', 'author_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment="创建者；'GUGA'=系统内置",
               existing_comment="创建者 user_id；'GUGA'=系统内置",
               existing_nullable=False)
    op.alter_column('mcp_servers', 'headers',
               existing_type=mysql.JSON(),
               comment='sse headers',
               existing_comment='sse: {"Authorization":"Bearer ..."}',
               existing_nullable=True)
    op.alter_column('mcp_servers', 'env',
               existing_type=mysql.JSON(),
               comment='stdio env',
               existing_comment='stdio: {"KEY":"value"}',
               existing_nullable=True)
    op.alter_column('mcp_servers', 'args',
               existing_type=mysql.JSON(),
               comment='stdio args',
               existing_comment='stdio: ["--arg1","val1"]',
               existing_nullable=True)
    op.alter_column('mcp_servers', 'transport',
               existing_type=mysql.ENUM('stdio', 'sse', 'streamable_http', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='连接方式',
               existing_nullable=False)
    op.alter_column('agents', 'type',
               existing_type=mysql.ENUM('claude', 'codex', 'opencode', 'custom', 'anthropic_sdk', collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='路由到对应 Adapter',
               existing_nullable=False)
    # ### end Alembic commands ###
